from tkinter import *
b=Tk()
b.title("intro")
b.geometry('1000x1000')
frame=Frame(b,bg="WHITE",bd=5,relief="solid")
frame.place(x=0,y=0,width=1520,height=1520)
l=Label(b,text="HOME PAGE",justify="right",font=("snap itc","24","bold"),bg="#C5B3D3",relief='solid')
l.place(x=400,y=0)
l=Label(b,text="Username",font=("calibri","16","bold"),bg="#F5CBCB",relief='solid')
l.place(x=10,y=50)
user=Entry(b,width=20,justify='center',font=("calibri","16","bold"))
user.place(x=155,y=55)

l=Label(b,text="Password",font=("calibri","16","bold"),bg="#F5CBCB",relief='solid')
l.place(x=10,y=100)
user=Entry(b,width=20,justify='center',show="*",font=("calibri","16","bold"))
user.place(x=155,y=100)
l=Label(b,text="Email",font=("calibri","16","bold"),bg="#F5CBCB",relief='solid')
l.place(x=10,y=150)
user=Entry(b,width=20,justify='center',show="*",font=("calibri","16","bold"))
user.place(x=155,y=150)
l1=Button(b,text="Next",font=("calibri","16","bold"),bg="#FFE2E2",relief='raised')
l1.place(x=650,y=200)
l1=Button(b,text="Cancel",font=("calibri","16","bold"),bg="#FFE2E2",relief='raised')
l1.place(x=750,y=200)
